import type { DataContract, SchemaTable } from '@/types/odcs'
import { ZEENEA_AUTH_DEF_TYPE } from '@/lib/p1Constants'
import { deriveContractId } from '@/lib/idDerivation'
import { migrateTableOdcsFields } from '@/lib/schemaOdcsMapping'

/** Contract exercising P1 fields for YAML and validation tests. */
export function buildP1FixtureContract(): DataContract {
  const now = new Date().toISOString()
  return {
    uid: 'p1-fixture',
    dataContractSpecification: '3.1.0',
    id: deriveContractId('Seller Payments v1', 'p1-fixture'),
    info: {
      title: 'Seller Payments v1',
      version: '1.1.0',
      domain: 'seller',
      owner: 'Data Platform',
      description: 'Views built on top of seller tables.',
      status: 'draft',
      tags: ['finance', 'sensitive'],
      descriptionUsage: 'Twice a day.',
      descriptionLimitations: 'Cannot be used in conjunction with full moon days.',
      descriptionAuthoritativeDefinitions: [{
        id: 'ad1',
        url: 'https://example.com/privacy',
        type: 'privacyStatement',
        description: 'Privacy',
      }],
    },
    customProperties: [{
      id: 'cp1',
      property: 'dataSteward',
      value: 'john.doe@example.com',
      description: 'Owner responsible for data quality.',
    }],
    dataset: [migrateTableOdcsFields({
      name: 'orders',
      physicalType: 'table',
      id: 'tbl-orders',
      physicalName: 'orders',
      quantumName: 'Payments Table',
      tableType: 'table',
      description: 'Provides core payment metrics',
      columns: [
        {
          id: 'tbl_orders_txn_ref_dt_prop',
          name: 'txn_ref_dt',
          physicalName: 'TXN_REF_DT',
          logicalName: 'Txn Ref Dt',
          physicalType: 'DATE',
          logicalType: 'date',
          required: true,
          isPrimaryKey: true,
          isPII: false,
          isUnique: false,
          criticalDataElement: false,
          description: 'A description for column rcvr_id.',
          examples: ['2022-10-03'],
          qualityRule: '',
          isUnknownType: false,
          quality: [{
            id: 'order_id_no_nulls',
            name: 'No nulls',
            description: 'There must be no null values.',
            type: 'text',
            dimension: 'completeness',
            severity: 'high',
            businessImpact: 'Reporting failure',
          }],
          tags: ['pii'],
          authoritativeDefinitions: [{
            id: 'z1',
            url: 'https://catalog.zeenea.example/actian/glossary/order',
            type: ZEENEA_AUTH_DEF_TYPE,
          }],
          foreignKey: { toTable: 'customers', toColumn: 'id' },
        },
        {
          id: 'tbl_orders_tags_prop',
          name: 'tags',
          physicalName: 'tags',
          logicalName: 'Tags',
          physicalType: 'JSON',
          logicalType: 'array',
          required: false,
          isPrimaryKey: false,
          isPII: false,
          isUnique: false,
          criticalDataElement: false,
          description: '',
          examples: [],
          qualityRule: '',
          isUnknownType: false,
          items: { logicalType: 'string' },
        },
      ],
      tags: ['Core'],
      quality: [{
        id: 'row_count',
        name: 'Row count',
        description: 'Table must have rows',
        type: 'text',
        dimension: 'coverage',
        aiVerified: true,
      }],
      authoritativeDefinitions: [{
        id: 'z2',
        url: 'https://catalog.zeenea.example/actian/lineage/orders',
        type: ZEENEA_AUTH_DEF_TYPE,
      }],
    } as SchemaTable), migrateTableOdcsFields({
      name: 'customers',
      physicalType: 'table',
      id: 'tbl-customers',
      physicalName: 'customers',
      quantumName: 'customers',
      tableType: 'table',
      description: 'Customers',
      columns: [{
        id: 'tbl_customers_id_prop',
        name: 'id',
        physicalName: 'id',
        logicalName: 'Id',
        physicalType: 'UUID',
        logicalType: 'string',
        required: true,
        isPrimaryKey: true,
        isPII: false,
        isUnique: true,
        criticalDataElement: false,
        description: '',
        examples: [],
        qualityRule: '',
        isUnknownType: false,
      }],
    } as SchemaTable)],
    stakeholders: [],
    roles: [{
      id: 'r1',
      role: 'microstrategy_user_opr',
      access: 'read',
      description: 'Read-only access',
    }],
    slaProperties: [{
      id: 'sla1',
      property: 'latency',
      value: '4',
      unit: 'h',
      element: 'orders.TXN_REF_DT',
      driver: 'regulatory',
      description: 'GA at 12.5.22',
    }],
    gitHistory: [],
    openPR: null,
    createdAt: now,
    updatedAt: now,
  }
}
